In [1]:
import pandas as pd

data = {
    "Name": ["Aman", "Riya", "Vikas"],
    "Dept": ["Sales", "HR", "IT"],
    "Age": [28, 32, 25]
}

df = pd.DataFrame(data)
print("Before:")
print(df)

df = df.rename(columns={"Name": "Employee_Name", "Dept": "Department"})

print("\nAfter:")
print(df)

Before:
    Name   Dept  Age
0   Aman  Sales   28
1   Riya     HR   32
2  Vikas     IT   25

After:
  Employee_Name Department  Age
0          Aman      Sales   28
1          Riya         HR   32
2         Vikas         IT   25

In [2]:
import pandas as pd

data = {
    "Name": ["Aman", "Riya", "Vikas"],
    "Dept": ["Sales", "HR", "IT"],
    "Age": [28, 32, 25]
}

df = pd.DataFrame(data)
print("Before:")
print(df)

# Rename specific columns
df = df.rename(columns={"Name": "Employee_Name", "Dept": "Department"})

# Convert all column names to lowercase
df_lower = df.rename(columns=str.lower)

# Convert all column names to uppercase
df_upper = df.rename(columns=str.upper)

print("\nAfter rename:")
print(df)

print("\nLowercase columns:")
print(df_lower)

print("\nUppercase columns:")
print(df_upper)

Before:
    Name   Dept  Age
0   Aman  Sales   28
1   Riya     HR   32
2  Vikas     IT   25

After rename:
  Employee_Name Department  Age
0          Aman      Sales   28
1          Riya         HR   32
2         Vikas         IT   25

Lowercase columns:
  employee_name department  age
0          Aman      Sales   28
1          Riya         HR   32
2         Vikas         IT   25

Uppercase columns:
  EMPLOYEE_NAME DEPARTMENT  AGE
0          Aman      Sales   28
1          Riya         HR   32
2         Vikas         IT   25

In [3]:
import pandas as pd

data = {"Age": ["28", "32", "thirty"]}
df = pd.DataFrame(data)
print(df.dtypes)

df["Age"] = pd.to_numeric(df["Age"], errors="coerce")
print(df.dtypes)
print(df)

Age    object
dtype: object
Age    float64
dtype: object
    Age
0  28.0
1  32.0
2   NaN

In [4]:
import pandas as pd

data = {"Amount": [100, 120, 110, 130, 5000]}  # 5000 is an outlier
df = pd.DataFrame(data)
print(df)

Q1 = df["Amount"].quantile(0.25)
Q3 = df["Amount"].quantile(0.75)
IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

outliers = df[(df["Amount"] < lower) | (df["Amount"] > upper)]
print("Outliers:\n", outliers)

clean_df = df[(df["Amount"] >= lower) & (df["Amount"] <= upper)]
print("Cleaned:\n", clean_df)

   Amount
0     100
1     120
2     110
3     130
4    5000
Outliers:
    Amount
4    5000
Cleaned:
    Amount
0     100
1     120
2     110
3     130

In [2]:
import pandas as pd
import numpy as np

data = {
    "Student Name": ["Amit", "Priya", "Rahul", "Priya", np.nan],
    "Age ": [20, 21, np.nan, 21, 19],
    " Marks": [85, 90, 78, 90, np.nan],
    "City": ["Jaipur", "Delhi", "Mumbai", "Delhi", "Pune"]
}

df = pd.DataFrame(data)
print(df)

  Student Name  Age    Marks    City
0         Amit  20.0    85.0  Jaipur
1        Priya  21.0    90.0   Delhi
2        Rahul   NaN    78.0  Mumbai
3        Priya  21.0    90.0   Delhi
4          NaN  19.0     NaN    Pune

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Student Name  4 non-null      object
 1   Age           4 non-null      float64
 2    Marks        4 non-null      float64
 3   City          5 non-null      object
dtypes: float64(2), object(2)
memory usage: 292.0+ bytes

In [4]:
df.describe()

            Age       Marks
count   4.000000   4.000000
mean   20.250000  85.750000
std     0.957427   5.678908
min    19.000000  78.000000
25%    19.750000  83.250000
50%    20.500000  87.500000
75%    21.000000  90.000000
max    21.000000  90.000000

In [5]:
df.isna()

   Student Name   Age    Marks   City
0         False  False   False  False
1         False  False   False  False
2         False   True   False  False
3         False  False   False  False
4          True  False    True  False

In [6]:
df.isna().sum()

Student Name    1
Age             1
 Marks          1
City            0
dtype: int64

In [7]:
df = df.drop_duplicates()
print(df)

  Student Name  Age    Marks    City
0         Amit  20.0    85.0  Jaipur
1        Priya  21.0    90.0   Delhi
2        Rahul   NaN    78.0  Mumbai
4          NaN  19.0     NaN    Pune

In [8]:
df = df.dropna()
print(df)

  Student Name  Age    Marks    City
0         Amit  20.0    85.0  Jaipur
1        Priya  21.0    90.0   Delhi

In [9]:
df = df.rename(columns={
    "Student Name": "student_name",
    "Age ": "age",
    " Marks": "marks",
    "City": "city"
})

print(df)

  student_name   age  marks    city
0         Amit  20.0   85.0  Jaipur
1        Priya  21.0   90.0   Delhi

In [10]:
print(df)

  student_name   age  marks    city
0         Amit  20.0   85.0  Jaipur
1        Priya  21.0   90.0   Delhi